"""empty message

Revision ID: ae35b71ddadb
Revises: 
Create Date: 2021-05-31 13:34:46.722704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae35b71ddadb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('coin_symbol', sa.String(), nullable=True),
    sa.Column('coin_name', sa.String(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('coin_symbol', sa.String(), nullable=True),
    sa.Column('coin_name', sa.String(), nullable=True),
    sa.Column('is_daily', sa.Integer(), nullable=True),
    sa.Column('time_daily', sa.Integer(), nullable=True),
    sa.Column('hourly_interval', sa.Integer(), nullable=True),
    sa.Column('last_send', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('tz_delta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('schedules')
    op.drop_table('alarms')
    # ### end Alembic commands ###
